/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProtectedJobsRouteImport } from './routes/_protected/jobs'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ApiSitemapRouteImport } from './routes/api/sitemap'
import { Route as ProtectedNovelsNewRouteImport } from './routes/_protected/novels/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCoversSplatRouteImport } from './routes/api/covers/$'
import { Route as ApiExportsSplatRouteImport } from './routes/api/exports/$'
import { Route as ApiV1NovelsRouteImport } from './routes/api/v1/novels'
import { Route as ProtectedNovelsNovelIdEditRouteImport } from './routes/_protected/novels/$novelId/edit'
import { Route as ProtectedNovelsNovelIdGlossaryRouteImport } from './routes/_protected/novels/$novelId/glossary'
import { Route as ProtectedNovelsNovelIdRelationshipsRouteImport } from './routes/_protected/novels/$novelId/relationships'
import { Route as PublicNovelsNovelIdIndexRouteImport } from './routes/_public/novels/$novelId/index'
import { Route as ApiV1BookmarksBookmarkIdRouteImport } from './routes/api/v1/bookmarks/$bookmarkId'
import { Route as ApiV1NovelsNovelIdRouteImport } from './routes/api/v1/novels/$novelId'
import { Route as PublicNovelsNovelIdChaptersChapterIdRouteImport } from './routes/_public/novels/$novelId/chapters/$chapterId'
import { Route as ApiV1NovelsNovelIdBookmarksRouteImport } from './routes/api/v1/novels/$novelId/bookmarks'
import { Route as ApiV1NovelsNovelIdChaptersRouteImport } from './routes/api/v1/novels/$novelId/chapters'
import { Route as ApiV1NovelsNovelIdCoverRouteImport } from './routes/api/v1/novels/$novelId/cover'
import { Route as ApiV1NovelsNovelIdManifestRouteImport } from './routes/api/v1/novels/$novelId/manifest'
import { Route as ApiV1NovelsNovelIdReaderStateRouteImport } from './routes/api/v1/novels/$novelId/reader-state'
import { Route as ApiV1NovelsNovelIdChaptersChapterIdRouteImport } from './routes/api/v1/novels/$novelId/chapters/$chapterId'
import { Route as ApiV1NovelsNovelIdChaptersChapterIdOpenRouteImport } from './routes/api/v1/novels/$novelId/chapters/$chapterId/open'
import { Route as ApiV1NovelsNovelIdChaptersChapterIdPositionRouteImport } from './routes/api/v1/novels/$novelId/chapters/$chapterId/position'
import { Route as ApiV1NovelsNovelIdChaptersChapterIdReadRouteImport } from './routes/api/v1/novels/$novelId/chapters/$chapterId/read'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedJobsRoute = ProtectedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapRoute = ApiSitemapRouteImport.update({
  id: '/api/sitemap',
  path: '/api/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedNovelsNewRoute = ProtectedNovelsNewRouteImport.update({
  id: '/novels/new',
  path: '/novels/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoversSplatRoute = ApiCoversSplatRouteImport.update({
  id: '/api/covers/$',
  path: '/api/covers/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportsSplatRoute = ApiExportsSplatRouteImport.update({
  id: '/api/exports/$',
  path: '/api/exports/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1NovelsRoute = ApiV1NovelsRouteImport.update({
  id: '/api/v1/novels',
  path: '/api/v1/novels',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedNovelsNovelIdEditRoute =
  ProtectedNovelsNovelIdEditRouteImport.update({
    id: '/novels/$novelId/edit',
    path: '/novels/$novelId/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedNovelsNovelIdGlossaryRoute =
  ProtectedNovelsNovelIdGlossaryRouteImport.update({
    id: '/novels/$novelId/glossary',
    path: '/novels/$novelId/glossary',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedNovelsNovelIdRelationshipsRoute =
  ProtectedNovelsNovelIdRelationshipsRouteImport.update({
    id: '/novels/$novelId/relationships',
    path: '/novels/$novelId/relationships',
    getParentRoute: () => ProtectedRoute,
  } as any)
const PublicNovelsNovelIdIndexRoute =
  PublicNovelsNovelIdIndexRouteImport.update({
    id: '/novels/$novelId/',
    path: '/novels/$novelId/',
    getParentRoute: () => PublicRoute,
  } as any)
const ApiV1BookmarksBookmarkIdRoute =
  ApiV1BookmarksBookmarkIdRouteImport.update({
    id: '/api/v1/bookmarks/$bookmarkId',
    path: '/api/v1/bookmarks/$bookmarkId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1NovelsNovelIdRoute = ApiV1NovelsNovelIdRouteImport.update({
  id: '/$novelId',
  path: '/$novelId',
  getParentRoute: () => ApiV1NovelsRoute,
} as any)
const PublicNovelsNovelIdChaptersChapterIdRoute =
  PublicNovelsNovelIdChaptersChapterIdRouteImport.update({
    id: '/novels/$novelId/chapters/$chapterId',
    path: '/novels/$novelId/chapters/$chapterId',
    getParentRoute: () => PublicRoute,
  } as any)
const ApiV1NovelsNovelIdBookmarksRoute =
  ApiV1NovelsNovelIdBookmarksRouteImport.update({
    id: '/bookmarks',
    path: '/bookmarks',
    getParentRoute: () => ApiV1NovelsNovelIdRoute,
  } as any)
const ApiV1NovelsNovelIdChaptersRoute =
  ApiV1NovelsNovelIdChaptersRouteImport.update({
    id: '/chapters',
    path: '/chapters',
    getParentRoute: () => ApiV1NovelsNovelIdRoute,
  } as any)
const ApiV1NovelsNovelIdCoverRoute = ApiV1NovelsNovelIdCoverRouteImport.update({
  id: '/cover',
  path: '/cover',
  getParentRoute: () => ApiV1NovelsNovelIdRoute,
} as any)
const ApiV1NovelsNovelIdManifestRoute =
  ApiV1NovelsNovelIdManifestRouteImport.update({
    id: '/manifest',
    path: '/manifest',
    getParentRoute: () => ApiV1NovelsNovelIdRoute,
  } as any)
const ApiV1NovelsNovelIdReaderStateRoute =
  ApiV1NovelsNovelIdReaderStateRouteImport.update({
    id: '/reader-state',
    path: '/reader-state',
    getParentRoute: () => ApiV1NovelsNovelIdRoute,
  } as any)
const ApiV1NovelsNovelIdChaptersChapterIdRoute =
  ApiV1NovelsNovelIdChaptersChapterIdRouteImport.update({
    id: '/$chapterId',
    path: '/$chapterId',
    getParentRoute: () => ApiV1NovelsNovelIdChaptersRoute,
  } as any)
const ApiV1NovelsNovelIdChaptersChapterIdOpenRoute =
  ApiV1NovelsNovelIdChaptersChapterIdOpenRouteImport.update({
    id: '/open',
    path: '/open',
    getParentRoute: () => ApiV1NovelsNovelIdChaptersChapterIdRoute,
  } as any)
const ApiV1NovelsNovelIdChaptersChapterIdPositionRoute =
  ApiV1NovelsNovelIdChaptersChapterIdPositionRouteImport.update({
    id: '/position',
    path: '/position',
    getParentRoute: () => ApiV1NovelsNovelIdChaptersChapterIdRoute,
  } as any)
const ApiV1NovelsNovelIdChaptersChapterIdReadRoute =
  ApiV1NovelsNovelIdChaptersChapterIdReadRouteImport.update({
    id: '/read',
    path: '/read',
    getParentRoute: () => ApiV1NovelsNovelIdChaptersChapterIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/terms': typeof TermsRoute
  '/jobs': typeof ProtectedJobsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/novels/new': typeof ProtectedNovelsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
  '/api/exports/$': typeof ApiExportsSplatRoute
  '/api/v1/novels': typeof ApiV1NovelsRouteWithChildren
  '/novels/$novelId/edit': typeof ProtectedNovelsNovelIdEditRoute
  '/novels/$novelId/glossary': typeof ProtectedNovelsNovelIdGlossaryRoute
  '/novels/$novelId/relationships': typeof ProtectedNovelsNovelIdRelationshipsRoute
  '/api/v1/bookmarks/$bookmarkId': typeof ApiV1BookmarksBookmarkIdRoute
  '/api/v1/novels/$novelId': typeof ApiV1NovelsNovelIdRouteWithChildren
  '/novels/$novelId/': typeof PublicNovelsNovelIdIndexRoute
  '/novels/$novelId/chapters/$chapterId': typeof PublicNovelsNovelIdChaptersChapterIdRoute
  '/api/v1/novels/$novelId/bookmarks': typeof ApiV1NovelsNovelIdBookmarksRoute
  '/api/v1/novels/$novelId/chapters': typeof ApiV1NovelsNovelIdChaptersRouteWithChildren
  '/api/v1/novels/$novelId/cover': typeof ApiV1NovelsNovelIdCoverRoute
  '/api/v1/novels/$novelId/manifest': typeof ApiV1NovelsNovelIdManifestRoute
  '/api/v1/novels/$novelId/reader-state': typeof ApiV1NovelsNovelIdReaderStateRoute
  '/api/v1/novels/$novelId/chapters/$chapterId': typeof ApiV1NovelsNovelIdChaptersChapterIdRouteWithChildren
  '/api/v1/novels/$novelId/chapters/$chapterId/open': typeof ApiV1NovelsNovelIdChaptersChapterIdOpenRoute
  '/api/v1/novels/$novelId/chapters/$chapterId/position': typeof ApiV1NovelsNovelIdChaptersChapterIdPositionRoute
  '/api/v1/novels/$novelId/chapters/$chapterId/read': typeof ApiV1NovelsNovelIdChaptersChapterIdReadRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/terms': typeof TermsRoute
  '/jobs': typeof ProtectedJobsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/novels/new': typeof ProtectedNovelsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
  '/api/exports/$': typeof ApiExportsSplatRoute
  '/api/v1/novels': typeof ApiV1NovelsRouteWithChildren
  '/novels/$novelId/edit': typeof ProtectedNovelsNovelIdEditRoute
  '/novels/$novelId/glossary': typeof ProtectedNovelsNovelIdGlossaryRoute
  '/novels/$novelId/relationships': typeof ProtectedNovelsNovelIdRelationshipsRoute
  '/api/v1/bookmarks/$bookmarkId': typeof ApiV1BookmarksBookmarkIdRoute
  '/api/v1/novels/$novelId': typeof ApiV1NovelsNovelIdRouteWithChildren
  '/novels/$novelId': typeof PublicNovelsNovelIdIndexRoute
  '/novels/$novelId/chapters/$chapterId': typeof PublicNovelsNovelIdChaptersChapterIdRoute
  '/api/v1/novels/$novelId/bookmarks': typeof ApiV1NovelsNovelIdBookmarksRoute
  '/api/v1/novels/$novelId/chapters': typeof ApiV1NovelsNovelIdChaptersRouteWithChildren
  '/api/v1/novels/$novelId/cover': typeof ApiV1NovelsNovelIdCoverRoute
  '/api/v1/novels/$novelId/manifest': typeof ApiV1NovelsNovelIdManifestRoute
  '/api/v1/novels/$novelId/reader-state': typeof ApiV1NovelsNovelIdReaderStateRoute
  '/api/v1/novels/$novelId/chapters/$chapterId': typeof ApiV1NovelsNovelIdChaptersChapterIdRouteWithChildren
  '/api/v1/novels/$novelId/chapters/$chapterId/open': typeof ApiV1NovelsNovelIdChaptersChapterIdOpenRoute
  '/api/v1/novels/$novelId/chapters/$chapterId/position': typeof ApiV1NovelsNovelIdChaptersChapterIdPositionRoute
  '/api/v1/novels/$novelId/chapters/$chapterId/read': typeof ApiV1NovelsNovelIdChaptersChapterIdReadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/cookie-policy': typeof CookiePolicyRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/terms': typeof TermsRoute
  '/_protected/jobs': typeof ProtectedJobsRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/novels/new': typeof ProtectedNovelsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
  '/api/exports/$': typeof ApiExportsSplatRoute
  '/api/v1/novels': typeof ApiV1NovelsRouteWithChildren
  '/_protected/novels/$novelId/edit': typeof ProtectedNovelsNovelIdEditRoute
  '/_protected/novels/$novelId/glossary': typeof ProtectedNovelsNovelIdGlossaryRoute
  '/_protected/novels/$novelId/relationships': typeof ProtectedNovelsNovelIdRelationshipsRoute
  '/api/v1/bookmarks/$bookmarkId': typeof ApiV1BookmarksBookmarkIdRoute
  '/api/v1/novels/$novelId': typeof ApiV1NovelsNovelIdRouteWithChildren
  '/_public/novels/$novelId/': typeof PublicNovelsNovelIdIndexRoute
  '/_public/novels/$novelId/chapters/$chapterId': typeof PublicNovelsNovelIdChaptersChapterIdRoute
  '/api/v1/novels/$novelId/bookmarks': typeof ApiV1NovelsNovelIdBookmarksRoute
  '/api/v1/novels/$novelId/chapters': typeof ApiV1NovelsNovelIdChaptersRouteWithChildren
  '/api/v1/novels/$novelId/cover': typeof ApiV1NovelsNovelIdCoverRoute
  '/api/v1/novels/$novelId/manifest': typeof ApiV1NovelsNovelIdManifestRoute
  '/api/v1/novels/$novelId/reader-state': typeof ApiV1NovelsNovelIdReaderStateRoute
  '/api/v1/novels/$novelId/chapters/$chapterId': typeof ApiV1NovelsNovelIdChaptersChapterIdRouteWithChildren
  '/api/v1/novels/$novelId/chapters/$chapterId/open': typeof ApiV1NovelsNovelIdChaptersChapterIdOpenRoute
  '/api/v1/novels/$novelId/chapters/$chapterId/position': typeof ApiV1NovelsNovelIdChaptersChapterIdPositionRoute
  '/api/v1/novels/$novelId/chapters/$chapterId/read': typeof ApiV1NovelsNovelIdChaptersChapterIdReadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookie-policy'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/terms'
    | '/jobs'
    | '/settings'
    | '/api/inngest'
    | '/api/sitemap'
    | '/novels/new'
    | '/api/auth/$'
    | '/api/covers/$'
    | '/api/exports/$'
    | '/api/v1/novels'
    | '/novels/$novelId/edit'
    | '/novels/$novelId/glossary'
    | '/novels/$novelId/relationships'
    | '/api/v1/bookmarks/$bookmarkId'
    | '/api/v1/novels/$novelId'
    | '/novels/$novelId/'
    | '/novels/$novelId/chapters/$chapterId'
    | '/api/v1/novels/$novelId/bookmarks'
    | '/api/v1/novels/$novelId/chapters'
    | '/api/v1/novels/$novelId/cover'
    | '/api/v1/novels/$novelId/manifest'
    | '/api/v1/novels/$novelId/reader-state'
    | '/api/v1/novels/$novelId/chapters/$chapterId'
    | '/api/v1/novels/$novelId/chapters/$chapterId/open'
    | '/api/v1/novels/$novelId/chapters/$chapterId/position'
    | '/api/v1/novels/$novelId/chapters/$chapterId/read'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookie-policy'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/terms'
    | '/jobs'
    | '/settings'
    | '/api/inngest'
    | '/api/sitemap'
    | '/novels/new'
    | '/api/auth/$'
    | '/api/covers/$'
    | '/api/exports/$'
    | '/api/v1/novels'
    | '/novels/$novelId/edit'
    | '/novels/$novelId/glossary'
    | '/novels/$novelId/relationships'
    | '/api/v1/bookmarks/$bookmarkId'
    | '/api/v1/novels/$novelId'
    | '/novels/$novelId'
    | '/novels/$novelId/chapters/$chapterId'
    | '/api/v1/novels/$novelId/bookmarks'
    | '/api/v1/novels/$novelId/chapters'
    | '/api/v1/novels/$novelId/cover'
    | '/api/v1/novels/$novelId/manifest'
    | '/api/v1/novels/$novelId/reader-state'
    | '/api/v1/novels/$novelId/chapters/$chapterId'
    | '/api/v1/novels/$novelId/chapters/$chapterId/open'
    | '/api/v1/novels/$novelId/chapters/$chapterId/position'
    | '/api/v1/novels/$novelId/chapters/$chapterId/read'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/cookie-policy'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/terms'
    | '/_protected/jobs'
    | '/_protected/settings'
    | '/api/inngest'
    | '/api/sitemap'
    | '/_public/'
    | '/_protected/novels/new'
    | '/api/auth/$'
    | '/api/covers/$'
    | '/api/exports/$'
    | '/api/v1/novels'
    | '/_protected/novels/$novelId/edit'
    | '/_protected/novels/$novelId/glossary'
    | '/_protected/novels/$novelId/relationships'
    | '/api/v1/bookmarks/$bookmarkId'
    | '/api/v1/novels/$novelId'
    | '/_public/novels/$novelId/'
    | '/_public/novels/$novelId/chapters/$chapterId'
    | '/api/v1/novels/$novelId/bookmarks'
    | '/api/v1/novels/$novelId/chapters'
    | '/api/v1/novels/$novelId/cover'
    | '/api/v1/novels/$novelId/manifest'
    | '/api/v1/novels/$novelId/reader-state'
    | '/api/v1/novels/$novelId/chapters/$chapterId'
    | '/api/v1/novels/$novelId/chapters/$chapterId/open'
    | '/api/v1/novels/$novelId/chapters/$chapterId/position'
    | '/api/v1/novels/$novelId/chapters/$chapterId/read'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  CookiePolicyRoute: typeof CookiePolicyRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  TermsRoute: typeof TermsRoute
  ApiInngestRoute: typeof ApiInngestRoute
  ApiSitemapRoute: typeof ApiSitemapRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCoversSplatRoute: typeof ApiCoversSplatRoute
  ApiExportsSplatRoute: typeof ApiExportsSplatRoute
  ApiV1NovelsRoute: typeof ApiV1NovelsRouteWithChildren
  ApiV1BookmarksBookmarkIdRoute: typeof ApiV1BookmarksBookmarkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/jobs': {
      id: '/_protected/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof ProtectedJobsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap': {
      id: '/api/sitemap'
      path: '/api/sitemap'
      fullPath: '/api/sitemap'
      preLoaderRoute: typeof ApiSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/novels/new': {
      id: '/_protected/novels/new'
      path: '/novels/new'
      fullPath: '/novels/new'
      preLoaderRoute: typeof ProtectedNovelsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/covers/$': {
      id: '/api/covers/$'
      path: '/api/covers/$'
      fullPath: '/api/covers/$'
      preLoaderRoute: typeof ApiCoversSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exports/$': {
      id: '/api/exports/$'
      path: '/api/exports/$'
      fullPath: '/api/exports/$'
      preLoaderRoute: typeof ApiExportsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/novels': {
      id: '/api/v1/novels'
      path: '/api/v1/novels'
      fullPath: '/api/v1/novels'
      preLoaderRoute: typeof ApiV1NovelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/novels/$novelId/edit': {
      id: '/_protected/novels/$novelId/edit'
      path: '/novels/$novelId/edit'
      fullPath: '/novels/$novelId/edit'
      preLoaderRoute: typeof ProtectedNovelsNovelIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/novels/$novelId/glossary': {
      id: '/_protected/novels/$novelId/glossary'
      path: '/novels/$novelId/glossary'
      fullPath: '/novels/$novelId/glossary'
      preLoaderRoute: typeof ProtectedNovelsNovelIdGlossaryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/novels/$novelId/relationships': {
      id: '/_protected/novels/$novelId/relationships'
      path: '/novels/$novelId/relationships'
      fullPath: '/novels/$novelId/relationships'
      preLoaderRoute: typeof ProtectedNovelsNovelIdRelationshipsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/novels/$novelId/': {
      id: '/_public/novels/$novelId/'
      path: '/novels/$novelId'
      fullPath: '/novels/$novelId/'
      preLoaderRoute: typeof PublicNovelsNovelIdIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/v1/bookmarks/$bookmarkId': {
      id: '/api/v1/bookmarks/$bookmarkId'
      path: '/api/v1/bookmarks/$bookmarkId'
      fullPath: '/api/v1/bookmarks/$bookmarkId'
      preLoaderRoute: typeof ApiV1BookmarksBookmarkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/novels/$novelId': {
      id: '/api/v1/novels/$novelId'
      path: '/$novelId'
      fullPath: '/api/v1/novels/$novelId'
      preLoaderRoute: typeof ApiV1NovelsNovelIdRouteImport
      parentRoute: typeof ApiV1NovelsRoute
    }
    '/_public/novels/$novelId/chapters/$chapterId': {
      id: '/_public/novels/$novelId/chapters/$chapterId'
      path: '/novels/$novelId/chapters/$chapterId'
      fullPath: '/novels/$novelId/chapters/$chapterId'
      preLoaderRoute: typeof PublicNovelsNovelIdChaptersChapterIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/v1/novels/$novelId/bookmarks': {
      id: '/api/v1/novels/$novelId/bookmarks'
      path: '/bookmarks'
      fullPath: '/api/v1/novels/$novelId/bookmarks'
      preLoaderRoute: typeof ApiV1NovelsNovelIdBookmarksRouteImport
      parentRoute: typeof ApiV1NovelsNovelIdRoute
    }
    '/api/v1/novels/$novelId/chapters': {
      id: '/api/v1/novels/$novelId/chapters'
      path: '/chapters'
      fullPath: '/api/v1/novels/$novelId/chapters'
      preLoaderRoute: typeof ApiV1NovelsNovelIdChaptersRouteImport
      parentRoute: typeof ApiV1NovelsNovelIdRoute
    }
    '/api/v1/novels/$novelId/cover': {
      id: '/api/v1/novels/$novelId/cover'
      path: '/cover'
      fullPath: '/api/v1/novels/$novelId/cover'
      preLoaderRoute: typeof ApiV1NovelsNovelIdCoverRouteImport
      parentRoute: typeof ApiV1NovelsNovelIdRoute
    }
    '/api/v1/novels/$novelId/manifest': {
      id: '/api/v1/novels/$novelId/manifest'
      path: '/manifest'
      fullPath: '/api/v1/novels/$novelId/manifest'
      preLoaderRoute: typeof ApiV1NovelsNovelIdManifestRouteImport
      parentRoute: typeof ApiV1NovelsNovelIdRoute
    }
    '/api/v1/novels/$novelId/reader-state': {
      id: '/api/v1/novels/$novelId/reader-state'
      path: '/reader-state'
      fullPath: '/api/v1/novels/$novelId/reader-state'
      preLoaderRoute: typeof ApiV1NovelsNovelIdReaderStateRouteImport
      parentRoute: typeof ApiV1NovelsNovelIdRoute
    }
    '/api/v1/novels/$novelId/chapters/$chapterId': {
      id: '/api/v1/novels/$novelId/chapters/$chapterId'
      path: '/$chapterId'
      fullPath: '/api/v1/novels/$novelId/chapters/$chapterId'
      preLoaderRoute: typeof ApiV1NovelsNovelIdChaptersChapterIdRouteImport
      parentRoute: typeof ApiV1NovelsNovelIdChaptersRoute
    }
    '/api/v1/novels/$novelId/chapters/$chapterId/open': {
      id: '/api/v1/novels/$novelId/chapters/$chapterId/open'
      path: '/open'
      fullPath: '/api/v1/novels/$novelId/chapters/$chapterId/open'
      preLoaderRoute: typeof ApiV1NovelsNovelIdChaptersChapterIdOpenRouteImport
      parentRoute: typeof ApiV1NovelsNovelIdChaptersChapterIdRoute
    }
    '/api/v1/novels/$novelId/chapters/$chapterId/position': {
      id: '/api/v1/novels/$novelId/chapters/$chapterId/position'
      path: '/position'
      fullPath: '/api/v1/novels/$novelId/chapters/$chapterId/position'
      preLoaderRoute: typeof ApiV1NovelsNovelIdChaptersChapterIdPositionRouteImport
      parentRoute: typeof ApiV1NovelsNovelIdChaptersChapterIdRoute
    }
    '/api/v1/novels/$novelId/chapters/$chapterId/read': {
      id: '/api/v1/novels/$novelId/chapters/$chapterId/read'
      path: '/read'
      fullPath: '/api/v1/novels/$novelId/chapters/$chapterId/read'
      preLoaderRoute: typeof ApiV1NovelsNovelIdChaptersChapterIdReadRouteImport
      parentRoute: typeof ApiV1NovelsNovelIdChaptersChapterIdRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedJobsRoute: typeof ProtectedJobsRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedNovelsNewRoute: typeof ProtectedNovelsNewRoute
  ProtectedNovelsNovelIdEditRoute: typeof ProtectedNovelsNovelIdEditRoute
  ProtectedNovelsNovelIdGlossaryRoute: typeof ProtectedNovelsNovelIdGlossaryRoute
  ProtectedNovelsNovelIdRelationshipsRoute: typeof ProtectedNovelsNovelIdRelationshipsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedJobsRoute: ProtectedJobsRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedNovelsNewRoute: ProtectedNovelsNewRoute,
  ProtectedNovelsNovelIdEditRoute: ProtectedNovelsNovelIdEditRoute,
  ProtectedNovelsNovelIdGlossaryRoute: ProtectedNovelsNovelIdGlossaryRoute,
  ProtectedNovelsNovelIdRelationshipsRoute:
    ProtectedNovelsNovelIdRelationshipsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicNovelsNovelIdIndexRoute: typeof PublicNovelsNovelIdIndexRoute
  PublicNovelsNovelIdChaptersChapterIdRoute: typeof PublicNovelsNovelIdChaptersChapterIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicNovelsNovelIdIndexRoute: PublicNovelsNovelIdIndexRoute,
  PublicNovelsNovelIdChaptersChapterIdRoute:
    PublicNovelsNovelIdChaptersChapterIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface ApiV1NovelsNovelIdChaptersChapterIdRouteChildren {
  ApiV1NovelsNovelIdChaptersChapterIdOpenRoute: typeof ApiV1NovelsNovelIdChaptersChapterIdOpenRoute
  ApiV1NovelsNovelIdChaptersChapterIdPositionRoute: typeof ApiV1NovelsNovelIdChaptersChapterIdPositionRoute
  ApiV1NovelsNovelIdChaptersChapterIdReadRoute: typeof ApiV1NovelsNovelIdChaptersChapterIdReadRoute
}

const ApiV1NovelsNovelIdChaptersChapterIdRouteChildren: ApiV1NovelsNovelIdChaptersChapterIdRouteChildren =
  {
    ApiV1NovelsNovelIdChaptersChapterIdOpenRoute:
      ApiV1NovelsNovelIdChaptersChapterIdOpenRoute,
    ApiV1NovelsNovelIdChaptersChapterIdPositionRoute:
      ApiV1NovelsNovelIdChaptersChapterIdPositionRoute,
    ApiV1NovelsNovelIdChaptersChapterIdReadRoute:
      ApiV1NovelsNovelIdChaptersChapterIdReadRoute,
  }

const ApiV1NovelsNovelIdChaptersChapterIdRouteWithChildren =
  ApiV1NovelsNovelIdChaptersChapterIdRoute._addFileChildren(
    ApiV1NovelsNovelIdChaptersChapterIdRouteChildren,
  )

interface ApiV1NovelsNovelIdChaptersRouteChildren {
  ApiV1NovelsNovelIdChaptersChapterIdRoute: typeof ApiV1NovelsNovelIdChaptersChapterIdRouteWithChildren
}

const ApiV1NovelsNovelIdChaptersRouteChildren: ApiV1NovelsNovelIdChaptersRouteChildren =
  {
    ApiV1NovelsNovelIdChaptersChapterIdRoute:
      ApiV1NovelsNovelIdChaptersChapterIdRouteWithChildren,
  }

const ApiV1NovelsNovelIdChaptersRouteWithChildren =
  ApiV1NovelsNovelIdChaptersRoute._addFileChildren(
    ApiV1NovelsNovelIdChaptersRouteChildren,
  )

interface ApiV1NovelsNovelIdRouteChildren {
  ApiV1NovelsNovelIdBookmarksRoute: typeof ApiV1NovelsNovelIdBookmarksRoute
  ApiV1NovelsNovelIdChaptersRoute: typeof ApiV1NovelsNovelIdChaptersRouteWithChildren
  ApiV1NovelsNovelIdCoverRoute: typeof ApiV1NovelsNovelIdCoverRoute
  ApiV1NovelsNovelIdManifestRoute: typeof ApiV1NovelsNovelIdManifestRoute
  ApiV1NovelsNovelIdReaderStateRoute: typeof ApiV1NovelsNovelIdReaderStateRoute
}

const ApiV1NovelsNovelIdRouteChildren: ApiV1NovelsNovelIdRouteChildren = {
  ApiV1NovelsNovelIdBookmarksRoute: ApiV1NovelsNovelIdBookmarksRoute,
  ApiV1NovelsNovelIdChaptersRoute: ApiV1NovelsNovelIdChaptersRouteWithChildren,
  ApiV1NovelsNovelIdCoverRoute: ApiV1NovelsNovelIdCoverRoute,
  ApiV1NovelsNovelIdManifestRoute: ApiV1NovelsNovelIdManifestRoute,
  ApiV1NovelsNovelIdReaderStateRoute: ApiV1NovelsNovelIdReaderStateRoute,
}

const ApiV1NovelsNovelIdRouteWithChildren =
  ApiV1NovelsNovelIdRoute._addFileChildren(ApiV1NovelsNovelIdRouteChildren)

interface ApiV1NovelsRouteChildren {
  ApiV1NovelsNovelIdRoute: typeof ApiV1NovelsNovelIdRouteWithChildren
}

const ApiV1NovelsRouteChildren: ApiV1NovelsRouteChildren = {
  ApiV1NovelsNovelIdRoute: ApiV1NovelsNovelIdRouteWithChildren,
}

const ApiV1NovelsRouteWithChildren = ApiV1NovelsRoute._addFileChildren(
  ApiV1NovelsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  CookiePolicyRoute: CookiePolicyRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  TermsRoute: TermsRoute,
  ApiInngestRoute: ApiInngestRoute,
  ApiSitemapRoute: ApiSitemapRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCoversSplatRoute: ApiCoversSplatRoute,
  ApiExportsSplatRoute: ApiExportsSplatRoute,
  ApiV1NovelsRoute: ApiV1NovelsRouteWithChildren,
  ApiV1BookmarksBookmarkIdRoute: ApiV1BookmarksBookmarkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
