import { mock } from "bun:test";
mock.module("server-only", () => ({}));

import { config } from "dotenv";
config({ path: ".env.local" });
config();

import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  console.error("DATABASE_URL is not set");
  process.exit(1);
}

async function run() {
  const client = postgres(connectionString!, {
    max: 1,
    onnotice: () => {},
  });

  try {
    console.log("Ensuring drizzle migration table structure...");
    await client`CREATE SCHEMA IF NOT EXISTS drizzle`;
    await client`
      CREATE TABLE IF NOT EXISTS drizzle.__drizzle_migrations (
        id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        hash text NOT NULL,
        created_at bigint
      )
    `;

    console.log("Applying database migrations...");
    const db = drizzle(client);
    await migrate(db, { migrationsFolder: "./drizzle" });
    console.log("Database migrations applied successfully!");
  } catch (err) {
    console.error("Migration failed:", err);
    process.exit(1);
  } finally {
    await client.end({ timeout: 1 });
    process.exit(0);
  }
}

run();
