/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedDesignScratchRouteImport } from './routes/_protected/design-scratch'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedNovelsNewRouteImport } from './routes/_protected/novels/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCoversSplatRouteImport } from './routes/api/covers/$'
import { Route as ApiCronTranslationWorkerRouteImport } from './routes/api/cron/translation-worker'
import { Route as ProtectedNovelsNovelIdIndexRouteImport } from './routes/_protected/novels/$novelId/index'
import { Route as ProtectedNovelsNovelIdEditRouteImport } from './routes/_protected/novels/$novelId/edit'
import { Route as ProtectedNovelsNovelIdGlossaryRouteImport } from './routes/_protected/novels/$novelId/glossary'
import { Route as ProtectedNovelsNovelIdChaptersChapterIdRouteImport } from './routes/_protected/novels/$novelId/chapters/$chapterId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDesignScratchRoute = ProtectedDesignScratchRouteImport.update({
  id: '/design-scratch',
  path: '/design-scratch',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedNovelsNewRoute = ProtectedNovelsNewRouteImport.update({
  id: '/novels/new',
  path: '/novels/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoversSplatRoute = ApiCoversSplatRouteImport.update({
  id: '/api/covers/$',
  path: '/api/covers/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronTranslationWorkerRoute =
  ApiCronTranslationWorkerRouteImport.update({
    id: '/api/cron/translation-worker',
    path: '/api/cron/translation-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedNovelsNovelIdIndexRoute =
  ProtectedNovelsNovelIdIndexRouteImport.update({
    id: '/novels/$novelId/',
    path: '/novels/$novelId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedNovelsNovelIdEditRoute =
  ProtectedNovelsNovelIdEditRouteImport.update({
    id: '/novels/$novelId/edit',
    path: '/novels/$novelId/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedNovelsNovelIdGlossaryRoute =
  ProtectedNovelsNovelIdGlossaryRouteImport.update({
    id: '/novels/$novelId/glossary',
    path: '/novels/$novelId/glossary',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedNovelsNovelIdChaptersChapterIdRoute =
  ProtectedNovelsNovelIdChaptersChapterIdRouteImport.update({
    id: '/novels/$novelId/chapters/$chapterId',
    path: '/novels/$novelId/chapters/$chapterId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/design-scratch': typeof ProtectedDesignScratchRoute
  '/settings': typeof ProtectedSettingsRoute
  '/novels/new': typeof ProtectedNovelsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
  '/api/cron/translation-worker': typeof ApiCronTranslationWorkerRoute
  '/novels/$novelId/edit': typeof ProtectedNovelsNovelIdEditRoute
  '/novels/$novelId/glossary': typeof ProtectedNovelsNovelIdGlossaryRoute
  '/novels/$novelId/': typeof ProtectedNovelsNovelIdIndexRoute
  '/novels/$novelId/chapters/$chapterId': typeof ProtectedNovelsNovelIdChaptersChapterIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/design-scratch': typeof ProtectedDesignScratchRoute
  '/settings': typeof ProtectedSettingsRoute
  '/': typeof ProtectedIndexRoute
  '/novels/new': typeof ProtectedNovelsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
  '/api/cron/translation-worker': typeof ApiCronTranslationWorkerRoute
  '/novels/$novelId/edit': typeof ProtectedNovelsNovelIdEditRoute
  '/novels/$novelId/glossary': typeof ProtectedNovelsNovelIdGlossaryRoute
  '/novels/$novelId': typeof ProtectedNovelsNovelIdIndexRoute
  '/novels/$novelId/chapters/$chapterId': typeof ProtectedNovelsNovelIdChaptersChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/design-scratch': typeof ProtectedDesignScratchRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/novels/new': typeof ProtectedNovelsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
  '/api/cron/translation-worker': typeof ApiCronTranslationWorkerRoute
  '/_protected/novels/$novelId/edit': typeof ProtectedNovelsNovelIdEditRoute
  '/_protected/novels/$novelId/glossary': typeof ProtectedNovelsNovelIdGlossaryRoute
  '/_protected/novels/$novelId/': typeof ProtectedNovelsNovelIdIndexRoute
  '/_protected/novels/$novelId/chapters/$chapterId': typeof ProtectedNovelsNovelIdChaptersChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/design-scratch'
    | '/settings'
    | '/novels/new'
    | '/api/auth/$'
    | '/api/covers/$'
    | '/api/cron/translation-worker'
    | '/novels/$novelId/edit'
    | '/novels/$novelId/glossary'
    | '/novels/$novelId/'
    | '/novels/$novelId/chapters/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/design-scratch'
    | '/settings'
    | '/'
    | '/novels/new'
    | '/api/auth/$'
    | '/api/covers/$'
    | '/api/cron/translation-worker'
    | '/novels/$novelId/edit'
    | '/novels/$novelId/glossary'
    | '/novels/$novelId'
    | '/novels/$novelId/chapters/$chapterId'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/design-scratch'
    | '/_protected/settings'
    | '/_protected/'
    | '/_protected/novels/new'
    | '/api/auth/$'
    | '/api/covers/$'
    | '/api/cron/translation-worker'
    | '/_protected/novels/$novelId/edit'
    | '/_protected/novels/$novelId/glossary'
    | '/_protected/novels/$novelId/'
    | '/_protected/novels/$novelId/chapters/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCoversSplatRoute: typeof ApiCoversSplatRoute
  ApiCronTranslationWorkerRoute: typeof ApiCronTranslationWorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/design-scratch': {
      id: '/_protected/design-scratch'
      path: '/design-scratch'
      fullPath: '/design-scratch'
      preLoaderRoute: typeof ProtectedDesignScratchRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/novels/new': {
      id: '/_protected/novels/new'
      path: '/novels/new'
      fullPath: '/novels/new'
      preLoaderRoute: typeof ProtectedNovelsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/covers/$': {
      id: '/api/covers/$'
      path: '/api/covers/$'
      fullPath: '/api/covers/$'
      preLoaderRoute: typeof ApiCoversSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/translation-worker': {
      id: '/api/cron/translation-worker'
      path: '/api/cron/translation-worker'
      fullPath: '/api/cron/translation-worker'
      preLoaderRoute: typeof ApiCronTranslationWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/novels/$novelId/': {
      id: '/_protected/novels/$novelId/'
      path: '/novels/$novelId'
      fullPath: '/novels/$novelId/'
      preLoaderRoute: typeof ProtectedNovelsNovelIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/novels/$novelId/edit': {
      id: '/_protected/novels/$novelId/edit'
      path: '/novels/$novelId/edit'
      fullPath: '/novels/$novelId/edit'
      preLoaderRoute: typeof ProtectedNovelsNovelIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/novels/$novelId/glossary': {
      id: '/_protected/novels/$novelId/glossary'
      path: '/novels/$novelId/glossary'
      fullPath: '/novels/$novelId/glossary'
      preLoaderRoute: typeof ProtectedNovelsNovelIdGlossaryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/novels/$novelId/chapters/$chapterId': {
      id: '/_protected/novels/$novelId/chapters/$chapterId'
      path: '/novels/$novelId/chapters/$chapterId'
      fullPath: '/novels/$novelId/chapters/$chapterId'
      preLoaderRoute: typeof ProtectedNovelsNovelIdChaptersChapterIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDesignScratchRoute: typeof ProtectedDesignScratchRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedNovelsNewRoute: typeof ProtectedNovelsNewRoute
  ProtectedNovelsNovelIdEditRoute: typeof ProtectedNovelsNovelIdEditRoute
  ProtectedNovelsNovelIdGlossaryRoute: typeof ProtectedNovelsNovelIdGlossaryRoute
  ProtectedNovelsNovelIdIndexRoute: typeof ProtectedNovelsNovelIdIndexRoute
  ProtectedNovelsNovelIdChaptersChapterIdRoute: typeof ProtectedNovelsNovelIdChaptersChapterIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDesignScratchRoute: ProtectedDesignScratchRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedNovelsNewRoute: ProtectedNovelsNewRoute,
  ProtectedNovelsNovelIdEditRoute: ProtectedNovelsNovelIdEditRoute,
  ProtectedNovelsNovelIdGlossaryRoute: ProtectedNovelsNovelIdGlossaryRoute,
  ProtectedNovelsNovelIdIndexRoute: ProtectedNovelsNovelIdIndexRoute,
  ProtectedNovelsNovelIdChaptersChapterIdRoute:
    ProtectedNovelsNovelIdChaptersChapterIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCoversSplatRoute: ApiCoversSplatRoute,
  ApiCronTranslationWorkerRoute: ApiCronTranslationWorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
