/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ProtectedNovelsNewRouteImport } from './routes/_protected/novels/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCoversSplatRouteImport } from './routes/api/covers/$'
import { Route as ProtectedNovelsNovelIdEditRouteImport } from './routes/_protected/novels/$novelId/edit'
import { Route as ProtectedNovelsNovelIdGlossaryRouteImport } from './routes/_protected/novels/$novelId/glossary'
import { Route as PublicNovelsNovelIdIndexRouteImport } from './routes/_public/novels/$novelId/index'
import { Route as PublicNovelsNovelIdChaptersChapterIdRouteImport } from './routes/_public/novels/$novelId/chapters/$chapterId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedNovelsNewRoute = ProtectedNovelsNewRouteImport.update({
  id: '/novels/new',
  path: '/novels/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoversSplatRoute = ApiCoversSplatRouteImport.update({
  id: '/api/covers/$',
  path: '/api/covers/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedNovelsNovelIdEditRoute =
  ProtectedNovelsNovelIdEditRouteImport.update({
    id: '/novels/$novelId/edit',
    path: '/novels/$novelId/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedNovelsNovelIdGlossaryRoute =
  ProtectedNovelsNovelIdGlossaryRouteImport.update({
    id: '/novels/$novelId/glossary',
    path: '/novels/$novelId/glossary',
    getParentRoute: () => ProtectedRoute,
  } as any)
const PublicNovelsNovelIdIndexRoute =
  PublicNovelsNovelIdIndexRouteImport.update({
    id: '/novels/$novelId/',
    path: '/novels/$novelId/',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicNovelsNovelIdChaptersChapterIdRoute =
  PublicNovelsNovelIdChaptersChapterIdRouteImport.update({
    id: '/novels/$novelId/chapters/$chapterId',
    path: '/novels/$novelId/chapters/$chapterId',
    getParentRoute: () => PublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof ProtectedSettingsRoute
  '/api/inngest': typeof ApiInngestRoute
  '/novels/new': typeof ProtectedNovelsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
  '/novels/$novelId/edit': typeof ProtectedNovelsNovelIdEditRoute
  '/novels/$novelId/glossary': typeof ProtectedNovelsNovelIdGlossaryRoute
  '/novels/$novelId/': typeof PublicNovelsNovelIdIndexRoute
  '/novels/$novelId/chapters/$chapterId': typeof PublicNovelsNovelIdChaptersChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof ProtectedSettingsRoute
  '/api/inngest': typeof ApiInngestRoute
  '/novels/new': typeof ProtectedNovelsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
  '/novels/$novelId/edit': typeof ProtectedNovelsNovelIdEditRoute
  '/novels/$novelId/glossary': typeof ProtectedNovelsNovelIdGlossaryRoute
  '/novels/$novelId': typeof PublicNovelsNovelIdIndexRoute
  '/novels/$novelId/chapters/$chapterId': typeof PublicNovelsNovelIdChaptersChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/api/inngest': typeof ApiInngestRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/novels/new': typeof ProtectedNovelsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
  '/_protected/novels/$novelId/edit': typeof ProtectedNovelsNovelIdEditRoute
  '/_protected/novels/$novelId/glossary': typeof ProtectedNovelsNovelIdGlossaryRoute
  '/_public/novels/$novelId/': typeof PublicNovelsNovelIdIndexRoute
  '/_public/novels/$novelId/chapters/$chapterId': typeof PublicNovelsNovelIdChaptersChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/api/inngest'
    | '/novels/new'
    | '/api/auth/$'
    | '/api/covers/$'
    | '/novels/$novelId/edit'
    | '/novels/$novelId/glossary'
    | '/novels/$novelId/'
    | '/novels/$novelId/chapters/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/api/inngest'
    | '/novels/new'
    | '/api/auth/$'
    | '/api/covers/$'
    | '/novels/$novelId/edit'
    | '/novels/$novelId/glossary'
    | '/novels/$novelId'
    | '/novels/$novelId/chapters/$chapterId'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/login'
    | '/_protected/settings'
    | '/api/inngest'
    | '/_public/'
    | '/_protected/novels/new'
    | '/api/auth/$'
    | '/api/covers/$'
    | '/_protected/novels/$novelId/edit'
    | '/_protected/novels/$novelId/glossary'
    | '/_public/novels/$novelId/'
    | '/_public/novels/$novelId/chapters/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiInngestRoute: typeof ApiInngestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCoversSplatRoute: typeof ApiCoversSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/novels/new': {
      id: '/_protected/novels/new'
      path: '/novels/new'
      fullPath: '/novels/new'
      preLoaderRoute: typeof ProtectedNovelsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/covers/$': {
      id: '/api/covers/$'
      path: '/api/covers/$'
      fullPath: '/api/covers/$'
      preLoaderRoute: typeof ApiCoversSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/novels/$novelId/edit': {
      id: '/_protected/novels/$novelId/edit'
      path: '/novels/$novelId/edit'
      fullPath: '/novels/$novelId/edit'
      preLoaderRoute: typeof ProtectedNovelsNovelIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/novels/$novelId/glossary': {
      id: '/_protected/novels/$novelId/glossary'
      path: '/novels/$novelId/glossary'
      fullPath: '/novels/$novelId/glossary'
      preLoaderRoute: typeof ProtectedNovelsNovelIdGlossaryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/novels/$novelId/': {
      id: '/_public/novels/$novelId/'
      path: '/novels/$novelId'
      fullPath: '/novels/$novelId/'
      preLoaderRoute: typeof PublicNovelsNovelIdIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/novels/$novelId/chapters/$chapterId': {
      id: '/_public/novels/$novelId/chapters/$chapterId'
      path: '/novels/$novelId/chapters/$chapterId'
      fullPath: '/novels/$novelId/chapters/$chapterId'
      preLoaderRoute: typeof PublicNovelsNovelIdChaptersChapterIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedNovelsNewRoute: typeof ProtectedNovelsNewRoute
  ProtectedNovelsNovelIdEditRoute: typeof ProtectedNovelsNovelIdEditRoute
  ProtectedNovelsNovelIdGlossaryRoute: typeof ProtectedNovelsNovelIdGlossaryRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedNovelsNewRoute: ProtectedNovelsNewRoute,
  ProtectedNovelsNovelIdEditRoute: ProtectedNovelsNovelIdEditRoute,
  ProtectedNovelsNovelIdGlossaryRoute: ProtectedNovelsNovelIdGlossaryRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicNovelsNovelIdIndexRoute: typeof PublicNovelsNovelIdIndexRoute
  PublicNovelsNovelIdChaptersChapterIdRoute: typeof PublicNovelsNovelIdChaptersChapterIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicNovelsNovelIdIndexRoute: PublicNovelsNovelIdIndexRoute,
  PublicNovelsNovelIdChaptersChapterIdRoute:
    PublicNovelsNovelIdChaptersChapterIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiInngestRoute: ApiInngestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCoversSplatRoute: ApiCoversSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
